// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ustpxphzldjzpmlgqqty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzdHB4cGh6bGRqenBtbGdxcXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MzQxMTcsImV4cCI6MjA1NTUxMDExN30.-dG0k4R8HQewREz5xYtAr3UP6EU-5IIsFZxf3ktItz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);